# This app.yaml is for deploying to instances of Cloud SQL running MySQL.
runtime: php72

env_variables:
  SQL_USER: "username"
  SQL_PASSWORD: "password"
  SQL_DSN: "mysql:dbname=dbname;unix_socket=/cloudsql/your-project-id:us-central1:instance-name"
